name: Deploy
on:
  workflow_call:
    inputs:
      produksjon:
        required: false
        type: boolean
        default: false
        description: Skal være true hvis det skal deployes til produksjon
      nais_cluster:
        required: false
        type: string
        default: gcp
        description: Nais cluster som applikasjonen skal deployes til. Skal enten være 'gcp' eller 'fss'
      nais_variabler_filnavn:
        required: false
        type: string
        default: feature.yaml
        description: Navnet på miljøvariabler filen som skal brukes ved deploy. Parameter skal inkludere filending som feks .yaml
      nais_hovedfil_navn:
        required: false
        type: string
        default: nais.yaml
        description: Navnet på nais filen som skal brukes. Parameter skal inkludere filending og evt path om det ikke ligger på root i .nais folder.
      docker_image:
        required: true
        type: string
        description: Docker Image navnet som skal deployes til miljø
    outputs:
      deploy_suksess:
        description: "Om deploy har gått gjennom OK"
        value: ${{ jobs.deploy.outputs.deploy_suksess }}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CLUSTER: ${{ inputs.produksjon && 'prod' || 'dev' }}-${{ inputs.nais_cluster }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ${{ inputs.nais_variabler_filnavn }}
    if: github.actor != 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v4
        with:
          path: deploy
      - name: Deploy to ${{ env.CLUSTER }} with ${{ inputs.nais_variabler_filnavn }}
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: deploy/.nais/${{ inputs.nais_hovedfil_navn }}
          VARS: deploy/.nais/${{ inputs.nais_variabler_filnavn }}
          IMAGE: ${{ inputs.docker_image }}
      - id: generate_outputs
        run: echo "deploy_suksess=true" >> $GITHUB_OUTPUT
    outputs:
      deploy_suksess: ${{ steps.generate_outputs.outputs.deploy_suksess }}