name: Deploy feature
on:
  workflow_call:
    inputs:
      nais_vars_file_name:
        required: true
        type: string
        default: feature
        description: Navnet på miljøvariabler filen som skal brukes ved deploy
    outputs:
      image:
        description: "Docker Image navnet som blir deployet til miljø"
        value: ${{ jobs.build.outputs.image }}
      tag:
        description: "Docker tag som blir deployet til miljø"
        value: ${{ jobs.build.outputs.tag }}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ENV_FILE_NAME: ${{ inputs.nais_vars_file_name }}

jobs:
  build_and_deploy:
    name: "Build and deploy to production"
    uses: ./.github/workflows/deploy_self_hosted.yaml
    with:
      nais_vars_file_name: ${{ inputs.nais_vars_file_name }}
      production: true
    secrets: inherit

  tag:
    name: "Tag release"
    needs: build_and_deploy
    if: ${{ always()  && needs.build_and_deploy.outputs.deploy_success == 'true' }}
    uses: ./.github/workflows/tag_release.yaml
    with:
      tag: ${{ needs.build_and_deploy.outputs.tag }}
    secrets: inherit