name: Deploy
on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: 21
        description: Hvilken versjon av java applikasjonen skal bygges med
      nais_cluster:
        required: false
        type: string
        default: gcp
        description: Skal enten være gcp eller fss
      nais_variabler_filnavn:
        required: false
        type: string
        default: prod.yaml
        description: Navnet på miljøvariabler filen som skal brukes ved deploy med filending
      maven_options:
        required: false
        type: string
        default: -B -q -fae
        description: Ekstra options ved kjøring av maven bygget. Dette kan være lag eller profiler. Default -B (Batchmode, non-interactive), -q (Quiet, kun logging ved errors), -fae (Fail at end).
    outputs:
      image:
        description: "Docker image som blir deployet til miljø"
        value: ${{ jobs.build_and_deploy.outputs.image }}
      tag:
        description: "Docker tag som blir deployet til miljø"
        value: ${{ jobs.build_and_deploy.outputs.tag }}

jobs:
  build_and_deploy:
    name: "Build and deploy to production"
    uses: ./.github/workflows/deploy.yaml
    with:
      nais_variabler_filnavn: ${{ inputs.nais_variabler_filnavn }}
      nais_cluster: ${{ inputs.nais_cluster }}
      produksjon: true
      java-version: ${{ inputs.java-version }}
      maven_options: ${{ inputs.maven_options }}
    secrets: inherit

  tag:
    name: "Tag release"
    needs: build_and_deploy
    uses: ./.github/workflows/tag_release.yaml
    with:
      tag: ${{ needs.build_and_deploy.outputs.tag }}
    secrets: inherit