name: Deploy feature
on:
  workflow_call:
    inputs:
      nais_variabler_filnavn:
        required: true
        type: string
        default: feature.yaml
        description: Navnet på miljøvariabler filen som skal brukes ved deploy med filending
      nais_hovedfil_navn:
        required: false
        type: string
        default: nais.yaml
        description: Navnet på nais filen som skal brukes. Parameter skal inkludere filending og evt path om det ikke ligger på root i .nais folder.
      maven_options:
        required: false
        type: string
        default: -B -q -fae
        description: Ekstra options ved kjøring av maven bygget. Dette kan være lag eller profiler. Default -B (Batchmode, non-interactive), -q (Quiet, kun logging ved errors), -fae (Fail at end).
      ktlint_options:
        required: false
        type: string
        description: Ektra parametere ved kjøring av ktlint.
      dockerfile_with_path:
        required: false
        type: string
        default: Dockerfile
        description: Kan settes for å spesifisere path for dockerfile.
      docker_context:
        required: false
        type: string
        default: .
        description: Kan settes for å spesifisere docker context for build files.
      image_suffix:
        required: false
        type: string
        description: Suffix for docker image om det er multimodul repo.
      tag:
        required: false
        type: string
        description: Custom docker tag
      slett_artifact:
        required: false
        type: boolean
        default: true
        description: Om det skal slettes opplastede artifact etter deploy
    outputs:
      image:
        description: "Docker Image navnet som blir deployet til miljø"
        value: ${{ jobs.build.outputs.image }}
      tag:
        description: "Docker tag som blir deployet til miljø"
        value: ${{ jobs.build.outputs.tag }}

jobs:
  build_and_deploy:
    name: "Build and deploy to production"
    uses: ./.github/workflows/deploy_self_hosted.yaml
    with:
      nais_variabler_filnavn: ${{ inputs.nais_variabler_filnavn }}
      nais_hovedfil_navn: ${{ inputs.nais_hovedfil_navn }}
      maven_options: ${{ inputs.maven_options }}
      produksjon: true
      ktlint_options: ${{ inputs.ktlint_options }}
      dockerfile_with_path: ${{ inputs.dockerfile_with_path }}
      docker_context: ${{ inputs.docker_context }}
      image_suffix: ${{ inputs.image_suffix }}
      tag: ${{ inputs.tag }}
      slett_artifact: ${{ inputs.slett_artifact }}
    secrets: inherit

  tag:
    name: "Tag release"
    needs: build_and_deploy
    if: ${{ always() && needs.build_and_deploy.outputs.deploy_suksess == 'true' }}
    uses: ./.github/workflows/tag_release.yaml
    with:
      tag: ${{ needs.build_and_deploy.outputs.tag }}
    secrets: inherit