name: Deploy feature
on:
  workflow_call:
    inputs:
      nais_variabler_filnavn:
        required: true
        type: string
        default: feature.yaml
        description: Navnet på miljøvariabler filen som skal brukes ved deploy med filending
    outputs:
      image:
        description: "Docker Image navnet som blir deployet til miljø"
        value: ${{ jobs.build.outputs.image }}
      tag:
        description: "Docker tag som blir deployet til miljø"
        value: ${{ jobs.build.outputs.tag }}

jobs:
  build_and_deploy:
    name: "Build and deploy to production"
    uses: ./.github/workflows/deploy_self_hosted.yaml
    with:
      nais_variabler_filnavn: ${{ inputs.nais_variabler_filnavn }}
      produksjon: true
    secrets: inherit

  tag:
    name: "Tag release"
    needs: build_and_deploy
    if: ${{ always() && needs.build_and_deploy.outputs.deploy_suksess == 'true' }}
    uses: ./.github/workflows/tag_release.yaml
    with:
      tag: ${{ needs.build_and_deploy.outputs.tag }}
    secrets: inherit