name: Release maven package
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: Versjon på pakken som skal publiseres
    outputs:
      published:
        description: "Om pakken er publisert"
        value: ${{ jobs.release.outputs.published }}
      version:
        description: "Versjon på pakken som ble publisert"
        value: ${{ jobs.release.outputs.version }}
env:
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
          server-password: GITHUB_TOKEN
          server-username: GITHUB_USERNAME
          server-id: github
      - name: Setting version
        run: |
          mvn versions:set -DnewVersion="${{ inputs.version }}"
          mvn versions:commit
      - name: Deploy to Github Package
        run: |
          echo "Release package with version ${{ inputs.version }}"
          mvn source:jar-no-fork deploy -DskipTests=true -Dmaven.wagon.http.pool=false -DdeployAtEnd=true
      - id: generate_outputs
        run: |
          echo "published=true" >> $GITHUB_OUTPUT
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
    outputs:
      published: ${{ steps.generate_outputs.outputs.published }}
      version: ${{ steps.generate_outputs.outputs.version }}