name: Rollback prod to previous version
on:
  workflow_call:
    inputs:
      nais_variabler_filnavn:
        required: false
        type: string
        default: prod.yaml
        description: Navnet på miljøvariabler filen som skal brukes ved deploy. Parameter skal inkludere filending som feks .yaml
      cluster:
        required: false
        type: string
        default: gcp
        description: Skal enten være gcp eller fss
      deploy_tag:
        required: false
        type: string
        description: Release tag som skal deployes. Som default vil forrige tag bli deployet
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CLUSTER: prod-${{ inputs.cluster }}

jobs:
  prepare_deploy:
    runs-on: ubuntu-latest
    name: Find tag to deploy

    steps:
      - uses: actions/checkout@v4
      - name: NAIS login
        uses: nais/login@v0
        id: login
        with:
          team: bidrag
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - id: deploy_version
        name: Find deploy version
        run: |
          git fetch --all --tags
          echo ${GITHUB_EVENT_NAME}
          REPO_NAME=${{github.event.repository.name}}
          DEPLOY_TAG=${{ inputs.deploy_tag }}
          if [ -z "$DEPLOY_TAG" ]; then 
           echo "NULL";
           DEPLOY_TAG=$(git tag -l | sort -V | tail -2 | head -1)
          fi
          echo "IMAGE=${{ steps.login.outputs.registry }}/$REPO_NAME:$DEPLOY_TAG" >> $GITHUB_OUTPUT
          echo "DEPLOY_TAG=$DEPLOY_TAG" >> $GITHUB_OUTPUT
    outputs:
      image: ${{ steps.deploy_version.outputs.IMAGE }}
      version: ${{ steps.deploy_version.outputs.DEPLOY_TAG }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy docker image to prod with variables from file ${{ inputs.nais_variabler_filnavn }}
    needs: prepare_deploy

    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: .nais/nais.yaml
          VARS: .nais/${{ inputs.nais_variabler_filnavn }}
          IMAGE: ${{ needs.prepare_deploy.outputs.image }}